### ISSUE TITLE
The schema element 'NavigationProperty' was not expected in the given context. 

### ISSUE THREAD

**Issue by scottdurow** [kenakamu/CRMLinqPadDriverWebAPI#10]
Running systemusers.Take(100)

Encountered the following errors when parsing the EDMX document: UnexpectedXmlElement : The schema element 'NavigationProperty' was not expected in the given context. : (1, 1502607)UnexpectedXmlElement : The schema element 'NavigationProperty' was not expected in the given context. : (1, 1543541)UnexpectedXmlElement : The schema element 'NavigationProperty' was not expected in the given context. : (1, 1665201)UnexpectedXmlElement : The schema element 'NavigationProperty' was not expected in the given context. : (1, 1669682)
--

**Comment by kenakamu** [comment]
Take didn't work for me too. Maybe the data contest doesn't support it?

**Comment by kenakamu** [comment]
Sorry it is working now with latest driver.

**Comment by DineshNanayakkara** [comment]
Hi @kenakamu , I think this issue is back. I am using the driver (Version 1.5.0.0).

**Comment by kenakamu** [comment]
Did you try using endpoint v8.2?

**Comment by DineshNanayakkara** [comment]
Yes, I was using endpoint version 8.2 since you updated to version 1.5.0.0. It stopped working not long ago.

**Comment by kenakamu** [comment]
It still works to me. Do all entities have the issue?

**Comment by koenvb** [comment]
Did not work for me either on 9.x API endpoint. Version 8.2 worked for me. 
What is the reason for the 9.x errors? Is that API not fully supported yet or does it not follow the new standards?

**Comment by kenakamu** [comment]
I personally not sure why but navigation won't work in a good way. Maybe T4 issue or version issue.

**Comment by ClientIco** [comment]
Hi I am also experiencing it with API 9.x API endpoint - Would it maybe be Microsoft changing something ?


Data | Data
-- | --
Errors | ReadOnlyCollection`1
HelpLink | null
HResult | -2146233088
InnerException | null
Message | Encountered the following errors when parsing the EDMX document: UnexpectedXmlElement : The schema element 'NavigationProperty' was not expected in the given context. : (1, 4250640)UnexpectedXmlElement : The schema element 'NavigationProperty' was not expected in the given context. : (1, 4410514)UnexpectedXmlElement : The schema element 'NavigationProperty' was not expected in the given context. : (1, 4431385)UnexpectedXmlElement : The schema element 'NavigationProperty' was not expected in the given context. : (1, 4436669)UnexpectedXmlElement : The schema element 'NavigationProperty' was not expected in the given context. : (1, 4436751)UnexpectedXmlElement : The schema element 'NavigationProperty' was not expected in the given context. : (1, 4437055)UnexpectedXmlElement : The schema element 'NavigationProperty' was not expected in the given context. : (1, 4449357)UnexpectedXmlElement : The schema element 'NavigationProperty' was not expected in the given context. : (1, 4449439)UnexpectedXmlElement : The schema element 'NavigationProperty' was not expect...
Source | Microsoft.OData.Edm
StackTrace | at Microsoft.OData.Edm.Csdl.EdmxReader.Parse(XmlReader reader, Func`2 getReferencedModelReaderFunc)   at Microsoft.Dynamics.CRM.System.GeneratedEdmModel.LoadModelFromString()   at Microsoft.Dynamics.CRM.System.GeneratedEdmModel..cctor()
TargetSite | TargetSite

This is on Account --> take(100)

**Comment by dipinb** [comment]
Did anyone fine a solution to this?  I've tried both the 9.x and 8.2 endpoint and I still get errors.  The 9.0 error is as others have written above.  The 8.2 error comes back with a "AuditDetail" method error.  Help!!!!

**Comment by dipinb** [comment]
I found a work around for this.  WARNING: It is brutal.  The following steps got my D365 Connections working:

1. Delete all connections that were connected to Dynamics 365
2. Delete the 1.5.0.0 driver
3. Install the 1.4.0.0 driver
4. Recreate all connections using the 1.4.0.0 driver
5. Download and install the 1.5.0.0 driver
6. Create the connections again with the same credentials used in step 3 above and ensure to use the 8.2 endpoint in the advanced settings.

At step 6 you will get an error (at least I did).  Just click "Submit" or "Cancel".  You should be left with the connections you created in step 3.  In other words, it shouldn't create a second set of duplicate connections after step 6.

Once I did this, I was able to browse the schema and execute queries.  Without doing these steps, I was getting another error that was preventing me from running any queries in the 8.2 endpoint.  

Anyways, hopefully this helps.  Hopefully somebody can implement a proper fix.
