### ISSUE TITLE
TypeInitializationException

### ISSUE THREAD

**Issue by DineshNanayakkara** [kenakamu/CRMLinqPadDriverWebAPI#13]
Hi,

I am using the Dynamics 365 (v 9.0) and getting this error even I do a simple query (e.g: accounts.Take(1))

```
Encountered the following errors when parsing the EDMX document: UnexpectedXmlElement : The schema element 'NavigationProperty' was not expected in the given context. : (1, 2079094)UnexpectedXmlElement : The schema element 'NavigationProperty' was not expected in the given context. : (1, 2224798)UnexpectedXmlElement : The schema element 'NavigationProperty' was not expected in the given context. : (1, 2245344) | Encountered the following errors when parsing the EDMX document: UnexpectedXmlElement : The schema element 'NavigationProperty' was not expected in the given context. : (1, 2079094)UnexpectedXmlElement : The schema element 'NavigationProperty' was not expected in the given context. : (1, 2224798)UnexpectedXmlElement : The schema element 'NavigationProperty' was not expected in the given context. : (1, 2245344)
-- | --
Encountered the following errors when parsing the EDMX document: UnexpectedXmlElement : The schema element 'NavigationProperty' was not expected in the given context. : (1, 2079094)UnexpectedXmlElement : The schema element 'NavigationProperty' was not expected in the given context. : (1, 2224798)UnexpectedXmlElement : The schema element 'NavigationProperty' was not expected in the given context. : (1, 2245344)

```
Have you ever encountered this and is there a fix I could apply to resolve this?

Thank you.

**Comment by kenakamu** [comment]
Take doesn't work as discussed in #10  but could you also try something different?

**Comment by kenakamu** [comment]
I could repro the issue with other simple query. It seems v9.0 endpoint is the cause and i am updating the driver to let you select version so that you can workaround it.

**Comment by DineshNanayakkara** [comment]
I have tried other query options too. Same result. :( Got, 

Encountered the following errors when parsing the EDMX document: UnexpectedXmlElement : The schema element 'NavigationProperty' was not expected in the given context. : (1, 2083309)UnexpectedXmlElement : The schema element 'NavigationProperty' was not expected in the given context. : (1, 2228794)UnexpectedXmlElement : The schema element 'NavigationProperty' was not expected in the given context. : (1, 2249340) | Encountered the following errors when parsing the EDMX document: UnexpectedXmlElement : The schema element 'NavigationProperty' was not expected in the given context. : (1, 2083309)UnexpectedXmlElement : The schema element 'NavigationProperty' was not expected in the given context. : (1, 2228794)UnexpectedXmlElement : The schema element 'NavigationProperty' was not expected in the given context. : (1, 2249340)
-- | --
Encountered the following errors when parsing the EDMX document: UnexpectedXmlElement : The schema element 'NavigationProperty' was not expected in the given context. : (1, 2083309)UnexpectedXmlElement : The schema element 'NavigationProperty' was not expected in the given context. : (1, 2228794)UnexpectedXmlElement : The schema element 'NavigationProperty' was not expected in the given context. : (1, 2249340)

**Comment by kenakamu** [comment]
Please update the driver to 1.5 and try by following [howto.md](https://github.com/kenakamu/CRMLinqPadDriverWebAPI/blob/master/HowTo.md)

**Comment by DineshNanayakkara** [comment]
Thank you for your valuable time. It's working now.

**Comment by PandaBoy00** [comment]
The issue with the NavigationProperty is the generated Edm file has the 'NavigationProperty' which it seems that with Dynamics 365 V9 doesn't like.  As a temporary workaround, you can go to the generated Edm file and change all 'NavigationProperty' to 'Property' for Type="mscrm.crmbaseentity" / Type="Collection(mscrm.crmbaseentity)" / Type="Collection(mscrm.email)" nodes under the ComplexType Parent Node and you should be fine.

Also in the CRMLinqPadDriverWebAPI version 1.5.0.0 is using the older ADAL version 2.29.  The updated ADAL 4.5.1.0 is more recent and has breaking changes in the code.

AcquireToken Method needs to be changed to AcquireTokenAsync and you can pass a Client Credential that takes a client id and client secret.

The method DiscoveryAuthority (MainWindowViewModel.cs) need to be updated to strip the '/oauth2/authorize' from the end of the AuthenticationParameters.Authority propety.  This is an error from the ADAL libraries from Microsoft.  Stripping the text will allow it to properly get the access token.  

CRMLinqPadDriver.cs and MainWindowViewModel.cs will need to change all AcquireToken method if the references to the ADAL is updated to 4.5.1.0

Would be good to update the UI to collect client id and client secret too.
