### ISSUE TITLE
SetState missing to reactivate records

### ISSUE THREAD

**Issue by PierreVicente** [kenakamu/CRMLinqPadDriverWebAPI#14]
I can use an update operation to change State and Status but that works only for active records.
If I want to reactivate a closed record, a call to SetState is required.
Am I missing something or is that method not implemented in the driver ?

**Comment by kenakamu** [comment]
The driver does not have any specific implementation but it only uses STK  The driver does not have any specific implementation but it only uses SDK underneath so if SDK can do it, the river should be able to do it otherwise cannot.

**Comment by PierreVicente** [comment]
Yes, SDK can reactivate closed quotes / salesorders / invoices, using SetStateRequest.
Apparently the driver does not implement a specific usage of SetStateRequest. Thus it is possible to deactivating a record by updating statecode and statuscode, but that won't work for reactivating a record.
Would you implement a specific SetState function that would execute a SetStateRequest ?

**Comment by kenakamu** [comment]
Could you share your code so that I can see the detail. As I said, I didn’t implement anything for the driver and no plan to do so in the future too. Everything should come from SDK itself

**Comment by PierreVicente** [comment]
Sorry for my late answer.
Here is how I have to deal:
1. recreate a CrmService Client object
_CrmServiceClient service = new CrmServiceClient("Url=https://xxxxx.crm4.dynamics.com; Username=admin@yyyy.onmicrosoft.com; Password=zzzz; AuthType=Office365");
	//service.Dump();_

2. later use that CrmServiceClient to execute a SetStateRequestMessage
_int state = lect.statecode;
int status = lect.statuscode;
if (state != 0)
{
    service.Execute(new SetStateRequest { EntityMoniker = new EntityReference(entete, lect.Id), State = new OptionSetValue(0), Status = new OptionSetValue(-1) });
}_

Is there a way to get a CrmServiceClient object directly in the Linqpad connection without recreating it ?
If not, It could be great to add a SetState function to the connection object.

Thanks.

**Comment by PierreVicente** [comment]
Finally, after exploring how the plugin creates objects and how it works, the best is to go on creating a separate CrmServiceClient and use it. 
My fear to change the connection in the query but keep the wrong organization in my CrmServiceClient object has been solved by that code:

string cnnUrl = this.BaseUri.Scheme + "://" + this.BaseUri.Host;
CrmServiceClient service = new CrmServiceClient("Url=" +cnnUrl + "; Username=adminxxx@yyyy.onmicrosoft.com; Password=zzzzzz; AuthType=Office365");

**Comment by kenakamu** [comment]
Yeah, the driver is based on WebAPI, not SDK. I am sorry to bring up SDK part that I am confused with another (old) driver which actually using SDK underneath. Anyway thanks !
