### ISSUE TITLE
System.NullReferenceException when connecting to CRM Online

### ISSUE THREAD

**Issue by TNSilverbear** [kenakamu/CRMLinqPadDriverWebAPI#4]
When creating a connection to as CRM Online instance I am receiving a System.NullReferenceException error thrown by Linqpad. This occurs during or potentially just after the dialog is showing the registering application message.

Any idea what may be causing this or where I could find more information to diagnose the issue?

**Comment by kenakamu** [comment]
Thanks for report.  Dis you try the latest version?

**Comment by kenakamu** [comment]
Tapped wrong button and closed this accidentally. Reopened

**Comment by TNSilverbear** [comment]
I've just re-downloaded the latest version an updated and still get the same issue I'm afraid.

**Comment by kenakamu** [comment]
Okay. Please let me know now detail repro steps and your environment detail so that I can think about the root cause.

**Comment by rajyraman** [comment]
I am having the exact same issue. It was working before in Windows 8 couple of months back. I have tried in both LinqPad 4/5. I was initially getting NullReference and now, no organisation is being added after "Registering Application" dialog.

**Comment by kenakamu** [comment]
please try the latest version (1.3) and let me know if it works

**Comment by TNSilverbear** [comment]
That appears to have resolved this issue, thank you. I am now receiving a different error message which I will raise as a separate issue.

**Comment by kenakamu** [comment]
Let me close it then.
