### ISSUE TITLE
Dynamics 365 Login/Metadata Issue

### ISSUE THREAD

**Issue by dipinb** [kenakamu/CRMLinqPadDriverWebAPI#5]
I'm having an issue with the login process with Dynamics 365.  When I try to login to Dynamcis 365, it looks like it recognizes my login, but it automatically returns me back to the login page without prompting me for the Azure AD login (which I was expecting) or downloading any metadata.  I'm able to connect no problem with Dynamics CRM 2016 Online in two different tenants, so it seems to be specific to Dynamics 365 and/or the 8.2 version of the Web API.  Any suggestions?

**Comment by kenakamu** [comment]
please try the latest version (1.3) and let me know if it works

**Comment by rajyraman** [comment]
Can you please let me know, where I can download the 1.3 version? Has this to be built from source?

**Comment by kenakamu** [comment]
You can download from inside LINQPad or from release tab of this GitHub repo.
Easiest way is to download from LINQPad.

Open LINQPad and click "add connection"
Click "View more drivers"
You find CRM Driver from there.

**Comment by dipinb** [comment]
Awesome!  Thank you!  Worked like a charm!

**Comment by kenakamu** [comment]
cool :)

**Comment by rajyraman** [comment]
That was the first thing I tried. But is it actually the most recent release? It says it was updated in April.

https://github.com/kenakamu/CRMLinqPadDriverWebAPI/releases/tag/Latest
http://www.linqpad.net/richclient/datacontextdrivers.aspx

**Comment by dipinb** [comment]
That was the way I downloaded it (from Linqpad just about an hour ago).  It updated the driver automatically with version 1.3.0.0.

**Comment by kenakamu** [comment]
The reason is that I need to keep the module link static so that LINQPad can pointing to same address.

**Comment by rajyraman** [comment]
Tried it on my personal laptop, even though it doesn't work on my work laptop (possibly some firewall rules). Thank for the the new release.

**Comment by kenakamu** [comment]
It should only use https port though
