### ISSUE TITLE
Cannot compile typed context

### ISSUE THREAD

**Issue by TNSilverbear** [kenakamu/CRMLinqPadDriverWebAPI#6]
When creating a connection I am receiving the following error. The instance of CRM I am connecting to is heavily customised, could this be hitting a limit in the mechanism of writing the context to file?

Cannot compile typed context: Unexpected error writing metadata to file
"{AppData/Local../LinqpadDriverWebAPI.../...}-1882896856ContextAlternative.dll" - 
No logical space left to create more user strings. (line 0)

**Comment by kenakamu** [comment]
This is interesting. According to http://stackoverflow.com/questions/1362635/c-sharp-compile-error-no-logical-space-left-to-create-more-user-strings, it seems to be a limitation of string so I may need to find a work around, I guess. I will create dummy metadata file which contains bunch of info to repro the issue. If I couldn't find good way, let's discuss.

**Comment by acornsoft** [comment]
Was this ever resolved, I have a case where this is blocking me from using it against a particular CRM tenant.  Would be more than willing to debug, if you can give me the best means to debug this driver.

**Comment by kenakamu** [comment]
Not yet. It is easier for me to have repro environment for Test

**Comment by acornsoft** [comment]
Anything I can do to help resolve?

**Comment by kenakamu** [comment]
I will add bunch of entities and fields to try to repro this weekend

**Comment by kenakamu** [comment]
Please try this one
https://github.com/kenakamu/CRMLinqPadDriverWebAPI/releases/tag/1.4

**Comment by TNSilverbear** [comment]
That works for me, thank you.

**Comment by kenakamu** [comment]
Great. It it works fine for a while, them I will publish it to LinqPad gallery.

**Comment by kenakamu** [comment]
officially released 1.4
