### ISSUE TITLE
CRM365+ADFS Authentication problem

### ISSUE THREAD

**Issue by mufus** [kenakamu/CRMLinqPadDriverWebAPI#8]
Running Linqpad v5.10 with latest version of this crm-driver (v1.4).
Our setup is Dynamics CRM 365 (v8.2) On-Premise with ADFS.

I fill out the ClientId, choose IFD + credentials. I get a list of our organizations, but after that, I get the error "Couldn't authenticate user. If you manually provided clientid, make sure it is registred as multi tenant application in case you access from different domain."

The error log on the ADFS-server gives us:

Encountered error during OAuth authorization request. 
Additional Data 
Exception details: 
Microsoft.IdentityServer.Web.Protocols.OAuth.Exceptions.OAuthInvalidResourceException: MSIS9329: Received invalid OAuth authorization request. The 'resource' parameter's value does not correspond to any valid registered relying party. Received resource: 'https://crm.mydomain.com/MYORG'. 
   at Microsoft.IdentityServer.Web.Protocols.OAuth.OAuthAuthorization.OAuthAuthorizationRequestContext.Validate()

Any ideas on this? We did the Add-AdfsClient command and restarted service.

**Comment by kenakamu** [comment]
I don't have environment right now for testing this. If you know how to debug, could you try to debug the issue? Otherwise I may need to access your environment if possible?
